# Generated by Django 5.0.2 on 2024-02-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.FileField(default='default/discover-04.jpg', upload_to='products/photo/%Y/%m/%d'),
        ),
    ]
