# Generated by Django 5.0.2 on 2024-02-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='owner',
            new_name='author',
        ),
        migrations.AddField(
            model_name='product',
            name='owner_full_name',
            field=models.CharField(max_length=56),
        ),
        migrations.AddField(
            model_name='product',
            name='owner_username',
            field=models.CharField(max_length=56),
        ),
    ]
